# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  RUNNER: "True"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V  # Print out python version for debugging
  - python -m pip install --upgrade pip
  - pip install virtualenv --upgrade
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.stfc.ac.uk/".insteadOf https://gitlab.stfc.ac.uk/


stages:
  - lint
  - docs

# auto-format code using black:
lint:
  stage: lint
  script:
  - pip install -r requirements.txt --upgrade
  - pylint -E --rcfile=setup.cfg setup.py hooks  # Pylint advanced linting (errors only)
  - flake8 setup.py hooks  # flake8 basic linting
  - isort --check setup.py hooks  # import sorting
  - black --check --diff .  # Black style checking
  - mypy hooks  # static type checking for type hints

lint_report:
  stage: lint
  script:
    - pip install -r requirements.txt --upgrade
    - pylint -r y --rcfile=setup.cfg --exit-zero hooks

# test the documentation builds for commits outside main branch:
test_doc:
  stage: docs
  script:
  - pip install -r requirements.txt --upgrade
  - python setup.py build_sphinx
  artifacts:
    paths:
    - doc/_build/html
  except:
  - main

# build the docs for main branch commits:
pages:
  stage: docs
  script:
  - pip install -r requirements.txt --upgrade
  - python setup.py build_sphinx
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - main
