# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/stfc/pre-commit-hooks
      rev: v0.3.7
      hooks:
        - id: check-mypy-import-errors
        - id: check-pylint-import-errors
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-toml
        - id: check-yaml
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-added-large-files
          name: check-add-large-files (notebooks)
          files: \.ipynb$
          args: [ '--maxkb=1000' ]
        - id: check-added-large-files
          name: check-add-large-files (images)
          files: \.(jpg|png|bmp|tif)$
          args: [ '--maxkb=1000' ]
        - id: check-added-large-files
          name: check-add-large-files (not notebooks or images)
          files: ^.+$(?<!\.jpg)(?<!\.png)(?<!\.ipynb)(?<!\.bmp)(?<!\.tif)
          args: [ '--maxkb=500' ]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.6.4
      hooks:
        - id: ruff-format  # The ruff code formatter
        - id: ruff # Run the linter.
          name: "ruff (lint)"
        - id: ruff # Run the import sorting
          name: "ruff (sort imports)"
          args: [ "--select", "I", "--fix" ]
