 -  id: check-missing-requirements
    name: Check for missing requirements from the environment
    entry: python -m hooks.check_missing_requirements
    language: system
    files: '^requirements.*\.txt$'
    always_run: true
 -  id: check-mypy-import-errors
    name: Check for mypy import errors
    entry: python -m hooks.check_mypy_import_errors
    language: system
    files: '^(requirements.*\.txt|pyproject.toml)$'
 -  id: check-pylint-import-errors
    name: Check for pylint import errors
    entry: python -m hooks.check_pylint_import_errors
    language: system
    types: [python]
    pass_filenames: false
