name: sphinx

on:
  push:
    tags: "*"
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install
        uses: abatilo/actions-poetry@v2.1.3
        run: poetry install --extras docs

      - name: Build documentation
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd doc/
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
